DROP TABLE FINES;

CREATE TABLE FINES (
    "LOAN_ID" VARCHAR PRIMARY KEY,
    FOREIGN KEY ("LOAN_ID") REFERENCES BOOK_LOANS("LOAN_ID"),
    "FINE_AMOUNT" FLOAT NOT NULL,
    "PAID" BOOLEAN NOT NULL
);

